package com.dbapp.ahcloud.adapter.model;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

/**
 * Table: address_object
 */
@Data
public class AddressObject implements Serializable {
    /**
     * 主键
     *
     * Table:     address_object
     * Column:    id
     * Nullable:  false
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * IP对象id
     *
     * Table:     address_object
     * Column:    ip_object_id
     * Nullable:  false
     */
    private String ipObjectId;

    /**
     * 对象名称
     *
     * Table:     address_object
     * Column:    name
     * Nullable:  false
     */
    private String name;

    /**
     * 对象描述
     *
     * Table:     address_object
     * Column:    description
     * Nullable:  false
     */
    private String description;

    /**
     * 租户id
     *
     * Table:     address_object
     * Column:    tenant_id
     * Nullable:  false
     */
    private String tenantId;

    /**
     * 是否删除，0：未删除，1：已删除
     *
     * Table:     address_object
     * Column:    is_deleted
     * Nullable:  false
     */
    private Integer isDeleted;

    /**
     * 创建时间
     *
     * Table:     address_object
     * Column:    gmt_create
     * Nullable:  false
     */
    private Date gmtCreate;

    /**
     * 修改时间
     *
     * Table:     address_object
     * Column:    gmt_modified
     * Nullable:  false
     */
    private Date gmtModified;

    /**
     * type-防护对象地址类型：network, range, host
address-防护对象的具体值
     *
     * Table:     address_object
     * Column:    object_list
     * Nullable:  false
     */
    private String objectList;

    /**
     * type-除外防护对象地址类型：network, range, host
address-除外防护对象的具体值
     *
     * Table:     address_object
     * Column:    except_object_list
     * Nullable:  false
     */
    private String exceptObjectList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address_object
     *
     * @mbggenerated Fri Sep 17 10:43:17 CST 2021
     */
    private static final long serialVersionUID = 1L;
}