package com.dbapp.ahcloud.adapter.model;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

/**
 * Table: ids_policy
 */
@Data
public class IdsPolicy implements Serializable {
    /**
     * 主键
     *
     * Table:     ids_policy
     * Column:    id
     * Nullable:  false
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * IDS策略id
     *
     * Table:     ids_policy
     * Column:    ids_policy_id
     * Nullable:  false
     */
    private String idsPolicyId;

    /**
     * 租户id
     *
     * Table:     ids_policy
     * Column:    tenant_id
     * Nullable:  false
     */
    private String tenantId;

    /**
     * 引用安全策略ID（列表），每个IPS策略对应至少一个安全策略
     *
     * Table:     ids_policy
     * Column:    security_policy_ids
     * Nullable:  false
     */
    private String securityPolicyIds;

    /**
     * IDS策略模板id（1：低级防护模板，2：中级防护模板，3：高级防护模板）
     *
     * Table:     ids_policy
     * Column:    ids_policy_template_id
     * Nullable:  false
     */
    private String idsPolicyTemplateId;

    /**
     * IDS策略模板名称
     *
     * Table:     ids_policy
     * Column:    ids_policy_template_name
     * Nullable:  false
     */
    private String idsPolicyTemplateName;

    /**
     * 是否启用，0:不启用，1:启用
     *
     * Table:     ids_policy
     * Column:    enable
     * Nullable:  false
     */
    private Integer enable;

    /**
     * 是否开启日志记录，0:不启用，1:启用
     *
     * Table:     ids_policy
     * Column:    logging
     * Nullable:  false
     */
    private Integer logging;

    /**
     * 策略名称
     *
     * Table:     ids_policy
     * Column:    name
     * Nullable:  false
     */
    private String name;

    /**
     * 策略描述
     *
     * Table:     ids_policy
     * Column:    description
     * Nullable:  false
     */
    private String description;

    /**
     * 是否删除，0：未删除，1：已删除
     *
     * Table:     ids_policy
     * Column:    is_deleted
     * Nullable:  false
     */
    private Integer isDeleted;

    /**
     * 创建时间
     *
     * Table:     ids_policy
     * Column:    gmt_create
     * Nullable:  false
     */
    private Date gmtCreate;

    /**
     * 修改时间
     *
     * Table:     ids_policy
     * Column:    gmt_modified
     * Nullable:  false
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ids_policy
     *
     * @mbggenerated Fri Sep 17 11:15:26 CST 2021
     */
    private static final long serialVersionUID = 1L;
}